### ISSUE TITLE
Slack >> Notion

### ISSUE THREAD

**Issue by arpitBhalla** [pranay01/request-for-startups#2]
Hey @pranay01 ,

Tried something with Notion & Slack, let me know what you think of it.

https://github.com/arpitBhalla/slack-notion

**Comment by pranay01** [comment]
@arpitBhalla Does it keep updating in  notion as new replies are added in Slack?

**Comment by arpitBhalla** [comment]
Hey @pranay01, Haven't added that, need to mention each time, I believe it might be doable, but AFAIK we need to listen for each incoming message in channel, and based on chat id, sync it with notion, which I think will use lot of server resource.
